### PR TITLE
适配于当前整体架构的FPN调整,输入为list,输出为tensor。

### PR DESCRIPTION
**Pull request by adolf69**

### CODE REVIEW

**Comment by adolf69** [comment]
适配于当前的FPN调整,输入为list,输出为tensor。
--

**Comment by adolf69** [comment]
from torchocr.networks.necks.FeaturePyramidNetwork import FeaturePyramidNetwork
neck_dict = {'FPN': FeaturePyramidNetwork}
我本地测试可以等价替换

**Comment by adolf69** [comment]
测试了下DB 
image

**Comment by WenmuZhou** [comment]
> from torchocr.networks.necks.FeaturePyramidNetwork import FeaturePyramidNetwork
> 
> neck_dict = {'FPN': FeaturePyramidNetwork}
> 
> 我本地测试可以等价替换

我明天看看，没问题就ok了

**Pull request merged**
